CREATE TABLE USERS (
  USER_NO NUMBER 				NOT NULL 
, USER_ID VARCHAR2(100 BYTE) 	NOT NULL 
, USER_PW VARCHAR2(200 BYTE) 	NOT NULL 
, NAME VARCHAR2(100 BYTE) 		NOT NULL 
, EMAIL VARCHAR2(200 BYTE) 
, REG_DATE DATE DEFAULT sysdate NOT NULL 
, UPD_DATE DATE DEFAULT sysdate NOT NULL 
, ENABLED NUMBER DEFAULT 1 		NOT NULL 
, CONSTRAINT USERS_PK PRIMARY KEY  (USER_NO)
);

COMMENT ON TABLE USERS IS '회원';
COMMENT ON COLUMN USERS.USER_NO IS '회원번호';
COMMENT ON COLUMN USERS.USER_ID IS '아이디';
COMMENT ON COLUMN USERS.USER_PW IS '비밀번호';
COMMENT ON COLUMN USERS.NAME IS '이름';
COMMENT ON COLUMN USERS.EMAIL IS '이메일';
COMMENT ON COLUMN USERS.REG_DATE IS '등록일자';
COMMENT ON COLUMN USERS.UPD_DATE IS '수정일자';
COMMENT ON COLUMN USERS.ENABLED IS '휴면여부';
