CREATE TABLE BOARD (
	  BOARD_NO NUMBER 				NOT NULL 
	, TITLE VARCHAR2(100 BYTE) 		NOT NULL 
	, CONTENT VARCHAR2(2000 BYTE) 
	, WRITER VARCHAR2(20 BYTE) 		NOT NULL 
	, REG_DATE DATE DEFAULT sysdate NOT NULL 
	, UPD_DATE DATE DEFAULT sysdate NOT NULL 
	, CONSTRAINT BOARD_PK PRIMARY KEY (BOARD_NO)
)
;
