CREATE TABLE USER_AUTH (
  AUTH_NO NUMBER NOT NULL 
, USER_ID VARCHAR2(100 BYTE) NOT NULL 
, AUTH VARCHAR2(100 BYTE) NOT NULL 
, CONSTRAINT USER_AUTH_PK PRIMARY KEY(AUTH_NO)
);

COMMENT ON TABLE USER_AUTH IS '회원 권한';
COMMENT ON COLUMN USER_AUTH.AUTH_NO IS '권한번호';
COMMENT ON COLUMN USER_AUTH.USER_ID IS '회원 아이디';
COMMENT ON COLUMN USER_AUTH.AUTH IS '권한';
